name: Setup Node Environment
description: Prepare repository, Node, and dependencies.
inputs:
  ref:
    description: Git ref to check out.
    required: false
    default: ''
runs:
  using: composite
  steps:
    - if: inputs.ref != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - if: inputs.ref == ''
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: npm
    - run: npm ci
