name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'manifest.json'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'manifest.json'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: npm test
